### ISSUE TITLE
FinnStonks currently crashes due to changes in used third party API

### ISSUE THREAD

**Issue by olaviinha** [olaviinha/PEPM#3]
Used exchange rates API (exchangeratesapi.io) has turned from free service to paid service. FinnStonks currently crashes due to missing API key. 

Will look into alternatives in the immdiate future.

**Comment by o-inha** [comment]
https://github.com/olaviinha/FinnStonks/commit/a82024f719016ac605a997c69e3f955e78a027af
https://github.com/olaviinha/FinnStonks/commit/11be0842b369af8f0f7e999ae5484f0066802ebe
